apps/home/urls.py
from django.conf.urls import url
from django.urls import path

from .views import HomeView, form_contacto_ajax, ServicioDetalleView

app_name = 'home'

urlpatterns = [
    path('', HomeView, name='home'),
    path('servicio/<slug:slug>/', ServicioDetalleView, name='detalle-servicio'),
    path('form/form_ajax/', form_contacto_ajax, name='form-contacto-ajax'),
]

apps/panel/urls.py
from django.conf.urls import url
from django.urls import path

from .views import PanelView, LogoutView, DetalleReclamoView, EnviarReclamoView, \
    form_enviar_reclamo_ajax, update_reclamo_ajax, respuesta_reclamo_ajax, ListarClientesView, \
    DetalleClienteView, crear_cliente_ajax, update_cliente_ajax, ContactoPanelView, \
    ServiciosPanelView, ServiciosEditarView, ServicioCrearView, EquipoListView, EquipoCreateView, \
    EquipoEditView, CertificacionListView, CertificacionCreateView, CertificacionEditView, ServiciosDeleteView, \
    EquipoDeleteView, CertificacionDeleteView, ContactonDeleteView, ListarUsuarios, crear_usuario_ajax, \
    update_usuario_ajax, DetalleUsuarioView, ClientesDeleteView, ListarInformesView, InformeEditView, \
    InformeCreateView, ListarInformesClienteView, login_success, get_filter_options, get_informe_chart, informe_per_category_chart

app_name = 'panel'

urlpatterns = [

    path('login_success/', login_success, name='login_success'),

    path('solicitudes/', PanelView, name="listar-solicitudes"),
    path('solicitud/<int:id>', DetalleReclamoView, name="detalle-reclamo"),
    path('solicitud/nuevo/', EnviarReclamoView, name="crear-reclamo"),
    path('form/form_ajax', form_enviar_reclamo_ajax, name='form-reclamo--ajax'),
    path('form/reclamo/form_ajax/<int:id>/', update_reclamo_ajax, name='form-update-reclamo-ajax'),
    path('form/respuesta/form_ajax/', respuesta_reclamo_ajax, name='form-respuesta-reclamo-ajax'),

    path('', ListarInformesView, name='panel'),
    path('my/informes/', ListarInformesClienteView, name="listar-informes-clientes"),
    path('informe/<int:id>', InformeEditView, name="editar-informe"),
    path('informe/nuevo/', InformeCreateView, name="crear-informe"),

    path('usuarios/', ListarUsuarios, name="listar-usuarios"),
    path('usuarios/nuevo/form_ajax/', crear_usuario_ajax, name="form-crear-usuario-por-ajax"),
    path('usuario/<int:id>', DetalleUsuarioView, name="detalle-usuario"),
    path('usuarios/editar/form_ajax/<int:id>/', update_usuario_ajax, name='form-update-usuario-ajax'),
    # path('usuarios/eliminar/<int:id>', UsuariosDeleteView, name="eliminar-usuario"),

    path('clientes/', ListarClientesView, name="listar-cliente"),
    path('cliente/<int:id>', DetalleClienteView, name="detalle-cliente"),
    path('cliente/nuevo/form_ajax/', crear_cliente_ajax, name='form-nuevo-cliente'),
    path('cliente/editar/form_ajax/<int:id>/', update_cliente_ajax, name='form-update-cliente-ajax'),
    path('cliente/eliminar/<int:id>/', ClientesDeleteView, name='eliminar-cliente'),

    path('modulo/contactos/', ContactoPanelView, name="listar-contactos"),
    path('modulo/contactos/eliminar/<int:id>', ContactonDeleteView, name="eliminar-contacto"),

    path('modulo/servcios/', ServiciosPanelView, name="listar-servicios"),
    path('modulo/servicio/<int:id>', ServiciosEditarView, name="detalle-servicio"),
    path('modulo/servicio/eliminar/<int:id>', ServiciosDeleteView, name="eliminar-servicio"),
    path('modulo/servicio/nuevo/', ServicioCrearView, name="crear-servicio"),

    path('modulo/equipo/', EquipoListView, name="listar-equipo"),
    path('modulo/equipo/nuevo/', EquipoCreateView, name="crear-equipo"),
    path('modulo/equipo/<int:id>', EquipoEditView, name="editar-equipo"),
    path('modulo/equipo/eliminar/<int:id>', EquipoDeleteView, name="eliminar-equipo"),

    path('modulo/certificaciones/', CertificacionListView, name="listar-certificacion"),
    path('modulo/certificaciones/nuevo/', CertificacionCreateView, name="crear-certificacion"),
    path('modulo/certificacion/<int:id>', CertificacionEditView, name="editar-certificacion"),
    path('modulo/certificacion/eliminar/<int:id>', CertificacionDeleteView, name="eliminar-certificado"),

    path('salir/', LogoutView, name="salir"),

    #url chart
    path('chart/filter-options/', get_filter_options, name='chart-filter-options'),
    path('chart/informes/<int:year>/', get_informe_chart, name='chart-informes'),
    path('chart/informes/tipo/<int:year>/', informe_per_category_chart, name='chart-informe-tipo'),
]

webecogestion/urls.py
import allauth
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', admin.site.urls),
    path('panel/',  include('apps.panel.urls', namespace='panel')),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth.account.views.LoginView, name='account_login'),
    path('tinymce/', include('tinymce.urls')),

    # url(r'^', include('apps.home.urls', namespace='home')),
    # url(r'^panel/', include('apps.panel.urls', namespace='panel')),
    # url(r'^accounts/', include('allauth.urls')),
    #
    # url(r'^accounts/login/', allauth.account.views.LoginView, name='account_login'),
    #
    # url(r'^tinymce/', include('tinymce.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

admin.site.site_header = 'Ecogestion Ambiental Ltda'

apps/home/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from tinymce.models import HTMLField

def upload_location(instance, filename):
    filebase, extension = filename.split(".")
    return "servicios/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_equipo(instance, filename):
    filebase, extension = filename.split(".")
    return "equipo/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_certificacion(instance, filename):
    filebase, extension = filename.split(".")
    return "certificacion/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_pdf(instance, filename):
    filebase, extension = filename.split(".")
    return "pdf/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

class Servcio(models.Model):
    CATEGORIA = (
        ('1', 'Vigilancia'),
        ('2', 'Estudios'),
        ('3', 'Monitoreos'),
        ('4', 'Laboratorio'),
    )
    nombre = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, max_length=1000, null=True, blank=True)
    categoria = models.CharField(choices=CATEGORIA, max_length=20)
    descripcion = HTMLField('Descripcion')
    img = models.ImageField(upload_to=upload_location,
                                  null=True,
                                  blank=True,
                                  editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

def create_slug(instance, new_slug=None):
    slug = slugify(instance.nombre)
    if new_slug is not None:
        slug = new_slug
    qs = Servcio.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_servicio_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_servicio_receiver, sender=Servcio)

class Equipo(models.Model):
    nombre_completo = models.CharField(max_length=100)
    cargo = models.CharField(max_length=50)
    url_twitter = models.URLField(blank=True, null=True)
    url_linkedin = models.URLField(blank=True, null=True)
    img = models.ImageField(upload_to=upload_location_equipo,
                            null=True,
                            blank=True,
                            editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre_completo

    class Meta:
        verbose_name = 'Integrante'
        verbose_name_plural = 'Integrantes'

class Certificacion(models.Model):
    nombre_certificacion = models.CharField(max_length=50)
    img = models.ImageField(upload_to=upload_location_certificacion,
                            null=True,
                            blank=True,
                            editable=True)
    pdf_file = models.FileField(upload_to=upload_location_pdf,
                                null=True,
                                blank=True,
                                editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre_certificacion

    class Meta:
        verbose_name = 'Certificación'
        verbose_name_plural = 'Certificaciones'

class Contacto(models.Model):
    TEMA = (
        ('1', 'Quejas'),
        ('2', 'Segerencias'),
        ('3', 'Cotizaciones'),
        ('4', 'Otro'),
    )
    nombre_completo = models.CharField(max_length=250)
    email = models.EmailField()
    fono = models.CharField(max_length=14)
    tema = models.CharField(max_length=250, choices=TEMA, blank=True, null=True)
    mensaje = models.TextField()
    fecha = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.nombre_completo

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

apps/informe/models.py
from django.db import models
from apps.cliente.models import Cliente

def upload_location_informe_pdf(instance, filename):
    filebase, extension = filename.split(".")
    return "informes/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

# Create your models here.
class Informe(models.Model):
    TIPO_INFORME = (
        ('1', 'Laboratorio de Ensayos'),
        ('2', 'Asesorías'),
        ('3', 'PVA'),
        ('4', 'Aguas Residuales'),
        ('5', 'Muestreo y/o Medición'),
        ('6', 'Aguas Subterráneas'),
        ('7', 'Agua Potable'),
    )
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre_informe = models.CharField(max_length=250, verbose_name="Nombre del Informe")
    tipo_informe = models.CharField(max_length=250, choices=TIPO_INFORME, verbose_name="Tipo de Informe")
    fecha_muestreo = models.DateField()
    fecha_recepcion = models.DateField()
    pdf_file = models.FileField(upload_to=upload_location_informe_pdf,
                                null=True,
                                blank=True,
                                editable=True)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    publicado = models.BooleanField(default=True)


    def __str__(self):
        return self.nombre_informe

    class Meta:
        verbose_name = 'Informe'
        verbose_name_plural = 'Informes'

apps/panel/models.py
from django.db import models

# Create your models here.

apps/reclamo/models.py
from django.db import models
from apps.cliente.models import Cliente
from django.contrib.auth.models import User

class Reclamo(models.Model):
    ESTADO = (
        ('1', 'Abierto'),
        ('2', 'En revisión'),
        ('3', 'Resuelto'),
        ('4', 'Cerrado'),
    )
    TIPO_SOLICITUD = (
        ('1', 'Queja'),
        ('2', 'Sugerencia'),
        ('3', 'Modificación de Informe'),

    )
    CAT = (
        ('1', 'Resultados de Ensayos'),
        ('2', 'Mediciones y muestreos'),
        ('3', 'Atención a clientes'),
        ('4', 'Logística'),
        ('5', 'Cotización'),
        ('6', 'Facturación'),
        ('7', 'Otros'),
    )
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    tipo_solicitud = models.CharField(choices=TIPO_SOLICITUD, max_length=25)
    estado = models.CharField(choices=ESTADO, max_length=25)
    categoria = models.CharField(choices=CAT, max_length=25)
    texto = models.TextField(max_length=600)
    fecha_ingreso = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __str__(self):
        return self.cliente.razon_social

    class Meta:
        verbose_name = 'Queja y Segerencia'
        verbose_name_plural = 'Quejas y Sugerencias'
        ordering = ["id"]

class Respuesta(models.Model):
    reclamo = models.ForeignKey(Reclamo, on_delete=models.CASCADE)
    usuario_interno = models.ForeignKey(User, on_delete=models.CASCADE)
    detalle_respuesta = models.TextField(max_length=600)
    fecha_respuesta = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.usuario_interno.username


    class Meta:
        verbose_name = 'Respuesta'
        verbose_name_plural = 'Respuestas'
        ordering = ["id"]

apps/panel/templates/include/filter-informe-staff.html
{% load widget_tweaks %}
<form method="get" id="form_filtros">
{#        {{ filter.form }}#}
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ filter.form.cliente.label_tag }}
            {% render_field filter.form.cliente class="form-control" %}
        </div>
        <div class="form-group col-md-4">
            {{ filter.form.tipo_informe.label_tag }}
            {% render_field filter.form.tipo_informe class="form-control" %}
        </div>
        <div class="form-group col-md-4">
            {{ filter.form.publicado.label_tag }}
            {% render_field filter.form.publicado class="form-control" %}
        </div>
    </div>
    <button type="submit" class="btn btn-primary" id="filtrar_datos" value="filtrar_datos"><i class="fa fa-filter"> </i> Filtrar</button>
    <button type="submit" class="btn btn-success" id="exportar_datos" value="exportar_datos"><i class="fa fa-file-excel"> </i> Exportar selección</button>
    <input type="hidden" id="accion_requerida" name="accion_requerida" value="">
</form>

apps/panel/templates/include/sidebar-cliente.html
<hr class="sidebar-divider">

<div class="sidebar-heading">
    Gestión de Informes
</div>

<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#informes" aria-expanded="true" aria-controls="informes">
        <i class="fas fa-fw fa-file-pdf"></i>
        <span>Informes</span>
    </a>
    <div id="informes" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Informes:</h6>
            <a class="collapse-item" href="{% url 'panel:listar-informes-clientes' %}">Mis Informes</a>
        </div>
    </div>
</li>

<hr class="sidebar-divider">

<div class="sidebar-heading">
    Gestión de Solicitudes
</div>

<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#reclamos" aria-expanded="true" aria-controls="reclamos">
        <i class="fas fa-fw fa-file-alt"></i>
        <span>Solicitudes</span>
    </a>
    <div id="reclamos" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Solicitudes:</h6>
            <a class="collapse-item" href="{% url 'panel:listar-solicitudes' %}">Ver todas mis solicitudes</a>
            <a class="collapse-item" href="{% url 'panel:crear-reclamo' %}">Ingresar una solicitud</a>

        </div>
    </div>
</li>

<hr class="sidebar-divider">

{#<hr class="sidebar-divider">#}

{#<div class="sidebar-heading">#}
{#    Gestión de empresas#}
{#</div>#}
{##}
{#<li class="nav-item">#}
{#    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#empresa" aria-expanded="true" aria-controls="empresa">#}
{#        <i class="fas fa-fw fa-building"></i>#}
{#        <span>Mis empresas</span>#}
{#    </a>#}
{#    <div id="empresa" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">#}
{#        <div class="bg-white py-2 collapse-inner rounded">#}
{#            <h6 class="collapse-header">Registro de empresas:</h6>#}
{#            <a class="collapse-item" href="#">Listar</a>#}
{#        </div>#}
{#    </div>#}
{#</li>#}

apps/panel/templates/include/tabla-certificados.html
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-xl-12 col-lg-12">
        {% if creado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ creado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        <!-- Mensaje para indicar que se ha editado con exito el convenio-->
        {% if editado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ editado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if eliminado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ eliminado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Mis Certificaciones</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Acciones:</div>
                        <a class="dropdown-item" href="{% url 'panel:crear-certificacion' %}">Nueva certificación</a>
                        <a href="{% url 'home:home' %}#certificaciones" class="dropdown-item" target="_blank">Ir a la Sección</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="table_datos" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Nombre certificación</th>
                            <th class="text-center">Logo</th>
                            <th class="text-center">Publicado</th>
                            <th class="text-center">Pdf</th>
                            <th class="text-center">Editar</th>
                            <th class="text-center">Eliminar</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Nombre certificación</th>
                            <th class="text-center">Logo</th>
                            <th class="text-center">Publicado</th>
                            <th class="text-center">Pdf</th>
                            <th class="text-center">Editar</th>
                            <th class="text-center">Eliminar</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for i  in mis_certificados %}
                            <tr>
                                <td>{{ i.nombre_certificacion }}</td>
                                {% if i.img %}
                                    <td>
                                        <img src="{{ i.img.url }}" alt="{{ i.nombre_certificacion }}" style="width: 250px">
                                    </td>
                                {% else %}
                                    <td>Sin foto</td>
                                {% endif %}
                                {% if i.publicado %}
                                    <td class="text-center"> Si </td>
                                {% else %}
                                    <td class="text-center"> No </td>
                                {% endif %}

                                <td class="text-center">
                                    {% if i.pdf_file %}
                                    <a href="{{ i.pdf_file.url }}" target="_blank" class="btn btn-secondary">
                                        <i class="fas fa-file-pdf"></i>
                                    </a>
                                        {% else %}
                                        <p>Sin archivo</p>
                                    {% endif %}
                                </td>

                                <td class="text-center">
                                    <a href="{% url 'panel:editar-certificacion' i.pk %}" class="btn btn-info">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'panel:eliminar-certificado' i.pk %}" class="btn btn-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

apps/panel/templates/include/tabla-detalle-reclamo.html
<div class="table-responsive">
    <table class="table table-striped">
        <tbody>
        <tr>
            <td>Nº</td>
            <td>{{ detalle_reclamo.pk }}</td>
        </tr>
        <tr>
            <td>Cliente</td>
            <td>{{ detalle_reclamo.cliente.razon_social }}</td>
        </tr>
        <tr>
            <th>Estado</th>
            <td>{{ detalle_reclamo.get_estado_display }}</td>
        </tr>
        <tr>
            <th>Fecha de Ingreso</th>
            <td>{{ detalle_reclamo.fecha_ingreso }}</td>
        </tr>
         <tr>
            <th>Tipo de Solicitud</th>
            <td>{{ detalle_reclamo.get_tipo_solicitud_display }}</td>
        </tr>
        <tr>
            <th>Categoría</th>
            <td>{{ detalle_reclamo.get_categoria_display }}</td>
        </tr>
        <tr>
            <th>Texto</th>
            <td>{{ detalle_reclamo.texto}}</td>
        </tr>
        </tbody>
    </table>

</div>

apps/panel/templates/include/tabla-equipo.html
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-xl-12 col-lg-12">
        {% if creado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ creado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        <!-- Mensaje para indicar que se ha editado con exito el convenio-->
        {% if editado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ editado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if eliminado %}
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ eliminado }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Mi Equipo</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Acciones:</div>
                        <a class="dropdown-item" href="{% url 'panel:crear-equipo' %}">Nuevo integrante</a>
                        <a href="{% url 'home:home' %}#equipo" class="dropdown-item" target="_blank">Ir a la Sección</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="table_datos" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Nombre Completo</th>
                            <th>Cargo</th>
                            <th>Foto</th>
                            <th class="text-center">Publicado</th>
                            <th class="text-center">Editar</th>
                            <th class="text-center">Eliminar</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Nombre Completo</th>
                            <th>Cargo</th>
                            <th>Foto</th>
                            <th class="text-center">Publicado</th>
                            <th class="text-center">Editar</th>
                            <th class="text-center">Eliminar</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for i  in mi_equipo %}
                            <tr>
                                <td>{{ i.nombre_completo }}</td>
                                <td>{{ i.cargo }}</td>
                                {% if i.img %}
                                    <td>
                                        <img src="{{ i.img.url }}" alt="{{ i.nombre_completo }}" style="width: 250px">
                                    </td>
                                {% else %}
                                    <td>Sin foto</td>
                                {% endif %}
                                {% if i.publicado %}
                                    <td class="text-center"> Si </td>
                                {% else %}
                                    <td class="text-center"> No </td>
                                {% endif %}

                                <td class="text-center">
                                    <a href="{% url 'panel:editar-equipo' i.pk %}" class="btn btn-info">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                </td>
                                 <td class="text-center">
                                    <a href="{% url 'panel:eliminar-equipo' i.pk %}" class="btn btn-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

apps/panel/templates/include/tabla-reclamos-staff.html
<div class="table-responsive">
    <table class="table table-bordered" id="table_datos" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Fecha de Ingreso</th>
            <th>Tipo de solicitud</th>
            <th>Categoria</th>
            <th>Estado</th>
            <th>Cliente</th>
             <th class="text-center">Detalles</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Fecha de Ingreso</th>
            <th>Tipo de solicitud</th>
            <th>Categoria</th>
            <th>Estado</th>
            <th>Cliente</th>
            <th class="text-center">Detalles</th>
        </tr>
        </tfoot>
        <tbody>
        {% for i  in filter.qs %}
        <tr>
            <td>{{ i.fecha_ingreso|date:'Y-m-d' }}</td>
            <td>{{ i.get_tipo_solicitud_display }}</td>
            <td>{{ i.get_categoria_display }}</td>
            <td>{{ i.get_estado_display }}</td>
            <td>{{ i.cliente }}</td>
            <td class="text-center">
                <a href="{% url 'panel:detalle-reclamo' i.pk %}" target="_blank" class="btn btn-info">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>