apps/home/urls.py
from django.conf.urls import url
from django.urls import path

from .views import HomeView, form_contacto_ajax, ServicioDetalleView

app_name = 'home'

urlpatterns = [
    path('', HomeView, name='home'),
    path('servicio/<slug:slug>/', ServicioDetalleView, name='detalle-servicio'),
    path('form/form_ajax/', form_contacto_ajax, name='form-contacto-ajax'),
]

webecogestion/urls.py
import allauth
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', admin.site.urls),
    path('panel/',  include('apps.panel.urls', namespace='panel')),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth.account.views.LoginView, name='account_login'),
    path('tinymce/', include('tinymce.urls')),

    # url(r'^', include('apps.home.urls', namespace='home')),
    # url(r'^panel/', include('apps.panel.urls', namespace='panel')),
    # url(r'^accounts/', include('allauth.urls')),
    #
    # url(r'^accounts/login/', allauth.account.views.LoginView, name='account_login'),
    #
    # url(r'^tinymce/', include('tinymce.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

admin.site.site_header = 'Ecogestion Ambiental Ltda'

apps/home/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from tinymce.models import HTMLField

def upload_location(instance, filename):
    filebase, extension = filename.split(".")
    return "servicios/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_equipo(instance, filename):
    filebase, extension = filename.split(".")
    return "equipo/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_certificacion(instance, filename):
    filebase, extension = filename.split(".")
    return "certificacion/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

def upload_location_pdf(instance, filename):
    filebase, extension = filename.split(".")
    return "pdf/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

class Servcio(models.Model):
    CATEGORIA = (
        ('1', 'Vigilancia'),
        ('2', 'Estudios'),
        ('3', 'Monitoreos'),
        ('4', 'Laboratorio'),
    )
    nombre = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, max_length=1000, null=True, blank=True)
    categoria = models.CharField(choices=CATEGORIA, max_length=20)
    descripcion = HTMLField('Descripcion')
    img = models.ImageField(upload_to=upload_location,
                                  null=True,
                                  blank=True,
                                  editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

def create_slug(instance, new_slug=None):
    slug = slugify(instance.nombre)
    if new_slug is not None:
        slug = new_slug
    qs = Servcio.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_servicio_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_servicio_receiver, sender=Servcio)

class Equipo(models.Model):
    nombre_completo = models.CharField(max_length=100)
    cargo = models.CharField(max_length=50)
    url_twitter = models.URLField(blank=True, null=True)
    url_linkedin = models.URLField(blank=True, null=True)
    img = models.ImageField(upload_to=upload_location_equipo,
                            null=True,
                            blank=True,
                            editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre_completo

    class Meta:
        verbose_name = 'Integrante'
        verbose_name_plural = 'Integrantes'

class Certificacion(models.Model):
    nombre_certificacion = models.CharField(max_length=50)
    img = models.ImageField(upload_to=upload_location_certificacion,
                            null=True,
                            blank=True,
                            editable=True)
    pdf_file = models.FileField(upload_to=upload_location_pdf,
                                null=True,
                                blank=True,
                                editable=True)
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre_certificacion

    class Meta:
        verbose_name = 'Certificación'
        verbose_name_plural = 'Certificaciones'

class Contacto(models.Model):
    TEMA = (
        ('1', 'Quejas'),
        ('2', 'Segerencias'),
        ('3', 'Cotizaciones'),
        ('4', 'Otro'),
    )
    nombre_completo = models.CharField(max_length=250)
    email = models.EmailField()
    fono = models.CharField(max_length=14)
    tema = models.CharField(max_length=250, choices=TEMA, blank=True, null=True)
    mensaje = models.TextField()
    fecha = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.nombre_completo

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

apps/home/forms.py
from django import forms
from .models import Contacto, Servcio, Equipo, Certificacion

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        exclude = ['fecha']
        fields = ['nombre_completo', 'email', 'fono', 'tema', 'mensaje']


class ServicioForm(forms.ModelForm):
    class Meta:
        model = Servcio
        exclude = ['slug']
        fields = ['nombre', 'categoria', 'descripcion', 'img', 'publicado']


class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ['nombre_completo', 'cargo', 'url_twitter', 'url_linkedin', 'img', 'publicado']


class CertificadoForm(forms.ModelForm):
    class Meta:
        model = Certificacion
        fields = ['nombre_certificacion', 'img', 'pdf_file', 'publicado']

apps/home/views.py
from urllib.parse import quote_plus

from django.core.mail import EmailMultiAlternatives
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template

from .models import Servcio, Equipo, Certificacion
from .forms import ContactoForm

def HomeView(request):
    data = dict()
    data['servicios'] = Servcio.objects.all().exclude(publicado=False).order_by('id')
    data['integrantes'] = Equipo.objects.all().exclude(publicado=False).order_by('id')
    data['certificaciones'] = Certificacion.objects.all().exclude(publicado=False).order_by('-id')
    data['form'] = ContactoForm()
    return render(request, 'home.html', data)

def ServicioDetalleView(request, slug):
    servicio = get_object_or_404(Servcio, slug=slug)
    if not servicio.publicado:
        raise Http404
    share_string = quote_plus(servicio.nombre)
    ctx = {
        'nombre_servicio': servicio.nombre,
        'servicio': servicio,
        'share_string': share_string,
    }
    return render(request, 'detalle-servicio.html', ctx)

def form_contacto_ajax(request):
    """
    Funcion que valida un formulario mediante ajax
    :param request: request.POST
    :return : Json
    """
    data = dict()

    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            # respuesta para el js
            data['respuesta'] = 'ok'

            # guardo la informacion de la solicitud
            form.save()

            # obtengo la informacion
            nombre_completo = request.POST['nombre_completo']
            email = request.POST['email']
            fono = request.POST['fono']
            mensaje = request.POST['mensaje']

            template = get_template('email/detalles-email-contacto.html')


            ctx = {
                'nombre_completo': nombre_completo,
                'email': email,
                'fono': fono,
                'mensaje': mensaje,

            }
            contenido = template.render(ctx)

            msg = EmailMultiAlternatives(
                'Contacto Web',
                contenido,
                'noresponder@ecogestionambiental.cl',
                ['jmoscoso@ecogestionambiental.cl'],
            )
            msg.attach_alternative(contenido, "text/html")

            msg.send()
        else:
            data['respuesta'] = 'error'
            mensaje_error = '<strong>Campos requeridos:</strong> <br>'
            for e in form.errors:
                mensaje_error = mensaje_error + ' [{}] '.format(e)
            data['mensaje'] = mensaje_error
    else:
        data['respuesta'] = 'error'

    return JsonResponse(data)

apps/home/templates/detalle-servicio.html
{% extends 'base.html' %}

{% block title %}
    {{ nombre_servicio }} | {{ block.super }}
{% endblock title %}

{% block header %}
    {% include 'include/header.html' %}
{% endblock header %}

{% block page-header %}
    {% include 'include/page-header.html' %}
{% endblock page-header %}

{% block servicios %}
    {% include 'include/info-detalle-servicios.html' %}
{% endblock servicios %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock footer %}

apps/home/templates/home.html
{% extends 'base.html' %}

{% block header %}
    {% include 'include/header.html' %}
{% endblock header %}

{% block page-header %}
    {% include 'include/page-header.html' %}
{% endblock page-header %}

{% block nosotros %}
    {% include 'include/nosotros.html' %}
{% endblock nosotros %}

{% block servicios %}
    {% include 'include/servicios.html' %}
{% endblock servicios %}

{% block equipo %}
    {% include 'include/equipo.html' %}
{% endblock equipo %}

{% block certificaciones %}
    {% include 'include/certificaiones.html' %}
{% endblock certificaciones %}

{% block contacto %}
    {% include 'include/contacto.html' %}
{% endblock contacto %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock footer %}

{% block custom-js %}
    <script>

        $(document).ready(function(){

            //form-contacto
            $('#div-errores').hide();

            $("#form-contacto").on("submit", function(){
                let csrftoken = $("[name=csrfmiddlewaretoken]").val();
                $('#btn-form-contacto').html('Enviando...');
                $.ajax({
                    url: "{% url 'home:form-contacto-ajax' %}",
                    type: 'POST',
                    data: $("#form-contacto").serialize(),
                    headers:{
                        "X-CSRFToken": csrftoken
                    },
                    success:function(data){
                        if(data.respuesta=='ok'){
                            let emisor = $('#id_nombre_completo').val();
                            $('#emisor').html(emisor);
                            $('#btn-form-contacto').html('Enviar');
                            $('#ContactonModal').modal('show');
                            $('#form-contacto')[0].reset();
                            $('#div-errores').hide();
                        }
                        else{//data.respuesta=='error'
                            $('#id_error').html('');
                            $('#id_error').html(data.mensaje);
                            $('#btn-form-contacto').html('Enviar');
                            $('#div-errores').show();
                        }
                    }
                });
                return false;
            });

        });
    </script>
{% endblock custom-js %}