apps/panel/urls.py
from django.conf.urls import url
from django.urls import path

from .views import PanelView, LogoutView, DetalleReclamoView, EnviarReclamoView, \
    form_enviar_reclamo_ajax, update_reclamo_ajax, respuesta_reclamo_ajax, ListarClientesView, \
    DetalleClienteView, crear_cliente_ajax, update_cliente_ajax, ContactoPanelView, \
    ServiciosPanelView, ServiciosEditarView, ServicioCrearView, EquipoListView, EquipoCreateView, \
    EquipoEditView, CertificacionListView, CertificacionCreateView, CertificacionEditView, ServiciosDeleteView, \
    EquipoDeleteView, CertificacionDeleteView, ContactonDeleteView, ListarUsuarios, crear_usuario_ajax, \
    update_usuario_ajax, DetalleUsuarioView, ClientesDeleteView, ListarInformesView, InformeEditView, \
    InformeCreateView, ListarInformesClienteView, login_success, get_filter_options, get_informe_chart, informe_per_category_chart

app_name = 'panel'

urlpatterns = [

    path('login_success/', login_success, name='login_success'),

    path('solicitudes/', PanelView, name="listar-solicitudes"),
    path('solicitud/<int:id>', DetalleReclamoView, name="detalle-reclamo"),
    path('solicitud/nuevo/', EnviarReclamoView, name="crear-reclamo"),
    path('form/form_ajax', form_enviar_reclamo_ajax, name='form-reclamo--ajax'),
    path('form/reclamo/form_ajax/<int:id>/', update_reclamo_ajax, name='form-update-reclamo-ajax'),
    path('form/respuesta/form_ajax/', respuesta_reclamo_ajax, name='form-respuesta-reclamo-ajax'),

    path('', ListarInformesView, name='panel'),
    path('my/informes/', ListarInformesClienteView, name="listar-informes-clientes"),
    path('informe/<int:id>', InformeEditView, name="editar-informe"),
    path('informe/nuevo/', InformeCreateView, name="crear-informe"),

    path('usuarios/', ListarUsuarios, name="listar-usuarios"),
    path('usuarios/nuevo/form_ajax/', crear_usuario_ajax, name="form-crear-usuario-por-ajax"),
    path('usuario/<int:id>', DetalleUsuarioView, name="detalle-usuario"),
    path('usuarios/editar/form_ajax/<int:id>/', update_usuario_ajax, name='form-update-usuario-ajax'),
    # path('usuarios/eliminar/<int:id>', UsuariosDeleteView, name="eliminar-usuario"),

    path('clientes/', ListarClientesView, name="listar-cliente"),
    path('cliente/<int:id>', DetalleClienteView, name="detalle-cliente"),
    path('cliente/nuevo/form_ajax/', crear_cliente_ajax, name='form-nuevo-cliente'),
    path('cliente/editar/form_ajax/<int:id>/', update_cliente_ajax, name='form-update-cliente-ajax'),
    path('cliente/eliminar/<int:id>/', ClientesDeleteView, name='eliminar-cliente'),

    path('modulo/contactos/', ContactoPanelView, name="listar-contactos"),
    path('modulo/contactos/eliminar/<int:id>', ContactonDeleteView, name="eliminar-contacto"),

    path('modulo/servcios/', ServiciosPanelView, name="listar-servicios"),
    path('modulo/servicio/<int:id>', ServiciosEditarView, name="detalle-servicio"),
    path('modulo/servicio/eliminar/<int:id>', ServiciosDeleteView, name="eliminar-servicio"),
    path('modulo/servicio/nuevo/', ServicioCrearView, name="crear-servicio"),

    path('modulo/equipo/', EquipoListView, name="listar-equipo"),
    path('modulo/equipo/nuevo/', EquipoCreateView, name="crear-equipo"),
    path('modulo/equipo/<int:id>', EquipoEditView, name="editar-equipo"),
    path('modulo/equipo/eliminar/<int:id>', EquipoDeleteView, name="eliminar-equipo"),

    path('modulo/certificaciones/', CertificacionListView, name="listar-certificacion"),
    path('modulo/certificaciones/nuevo/', CertificacionCreateView, name="crear-certificacion"),
    path('modulo/certificacion/<int:id>', CertificacionEditView, name="editar-certificacion"),
    path('modulo/certificacion/eliminar/<int:id>', CertificacionDeleteView, name="eliminar-certificado"),

    path('salir/', LogoutView, name="salir"),

    #url chart
    path('chart/filter-options/', get_filter_options, name='chart-filter-options'),
    path('chart/informes/<int:year>/', get_informe_chart, name='chart-informes'),
    path('chart/informes/tipo/<int:year>/', informe_per_category_chart, name='chart-informe-tipo'),
]

webecogestion/urls.py
import allauth
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', admin.site.urls),
    path('panel/',  include('apps.panel.urls', namespace='panel')),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth.account.views.LoginView, name='account_login'),
    path('tinymce/', include('tinymce.urls')),

    # url(r'^', include('apps.home.urls', namespace='home')),
    # url(r'^panel/', include('apps.panel.urls', namespace='panel')),
    # url(r'^accounts/', include('allauth.urls')),
    #
    # url(r'^accounts/login/', allauth.account.views.LoginView, name='account_login'),
    #
    # url(r'^tinymce/', include('tinymce.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

admin.site.site_header = 'Ecogestion Ambiental Ltda'

apps/informe/models.py
from django.db import models
from apps.cliente.models import Cliente

def upload_location_informe_pdf(instance, filename):
    filebase, extension = filename.split(".")
    return "informes/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

# Create your models here.
class Informe(models.Model):
    TIPO_INFORME = (
        ('1', 'Laboratorio de Ensayos'),
        ('2', 'Asesorías'),
        ('3', 'PVA'),
        ('4', 'Aguas Residuales'),
        ('5', 'Muestreo y/o Medición'),
        ('6', 'Aguas Subterráneas'),
        ('7', 'Agua Potable'),
    )
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre_informe = models.CharField(max_length=250, verbose_name="Nombre del Informe")
    tipo_informe = models.CharField(max_length=250, choices=TIPO_INFORME, verbose_name="Tipo de Informe")
    fecha_muestreo = models.DateField()
    fecha_recepcion = models.DateField()
    pdf_file = models.FileField(upload_to=upload_location_informe_pdf,
                                null=True,
                                blank=True,
                                editable=True)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    publicado = models.BooleanField(default=True)


    def __str__(self):
        return self.nombre_informe

    class Meta:
        verbose_name = 'Informe'
        verbose_name_plural = 'Informes'

templates/base-dashboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/assets/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'dashboard/assets/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    <!-- select2 -->
    <link href="{% static 'assets/css/select2.css' %}" rel="stylesheet" />

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% block sidebar %}
        {% include 'include/sidebar.html' %}
    {% endblock sidebar %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            {% block nav %}
                {% include 'include/nav.html' %}
            {% endblock nav %}
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                {% block panel-title %}
                    {% include 'include/panel-title.html' %}
                {% endblock panel-title %}

                <!-- Content Row -->
                {% block content %}
                {% endblock content %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        {% block footer %}
            {% include 'include/footer-panel.html' %}
        {% endblock footer %}
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Desea salir del sistema?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Haz clic sobre el botón "Salir" para finalizar la sesión actual.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'panel:salir' %}">Salir</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'dashboard/assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'dashboard/assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugins -->
{#<script src="{% static 'dashboard/assets/vendor/chart.js/Chart.min.js' %}"></script>#}
<script src="{% static 'dashboard/assets/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'dashboard/assets/js/sb-admin-2.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/demo/datatables-demo.js' %}"></script>

<!-- select2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<!-- Chart -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>


{% block custom-js %}
    <script>
        $(document).ready(function() {
            $('#table_datos').DataTable({
                "order": [],
                "language": {
                    "lengthMenu": "Ver _MENU_ registros",
                    "loadingRecords": "Loading...",
                    "processing": "Processing...",
                    "search": "Buscar:",
                    "zeroRecords": "No se ha encontrado en la busqueda",
                    "emptyTable": "No hay datos disponibles en la tabla",
                    "info": "Visibles _START_ a _END_ de _TOTAL_ Registros",
                    "infoEmpty": "Visibles 0 a 0 de 0 Registros",
                    "paginate": {
                        "first": "Primera",
                        "last": "Última",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }

                }

            });
            //-------------------------
        });
    </script>
    <script>
        $('#filtrar_datos, #exportar_datos').click(function(e){
            $('#accion_requerida').val(this.id);
            $('#form_filtros').submit();
        });
    </script>
    <script>
        $(document).ready(function() {
            $('#id_cliente').select2({width:'100%', placeholder: "Seleccione un cliente" });
        });
    </script>

    <script>
        let informeCtx = document.getElementById("InformeChart").getContext("2d");
        let InformeChart = new Chart(informeCtx, {
            type: "bar",
            options: {
                responsive: true,
                tooltips: {
                    enabled: true,
                    mode: 'nearest',
                    intersect: true,
                },
                legend: {
                    display: true,
                }
            },

        });
        let TipoInformeCtx = document.getElementById("TipoInformeChart").getContext("2d");
        let TipoInformeChart = new Chart(TipoInformeCtx, {
            type: "doughnut",
            options: {
                responsive: true,
                tooltips: {
                    enabled: true,
                    mode: 'nearest',
                    intersect: true,
                },
                legend: {
                    display: true,
                },
            }

        });
    </script>
    <script>
        $(document).ready(function() {
            $.ajax({
                url: "/panel/chart/filter-options/",
                type: "GET",
                dataType: "json",
                success: (jsonResponse) => {
                    // Load all the options
                    jsonResponse.options.forEach(option => {
                        $("#year").append(new Option(option, option));
                    });
                    // Load data for the first option
                    loadAllCharts($("#year").children().first().val());
                },
                error: () => console.log("Failed to fetch chart filter options!")
            });
        });

        $("#filterForm").on("submit", (event) => {
            event.preventDefault();

            const year = $("#year").val();
            loadAllCharts(year)
        });
        function loadChart(chart, endpoint) {
            $.ajax({
                url: endpoint,
                type: "GET",
                dataType: "json",
                success: (jsonResponse) => {
                    // Extract data from the response
                    const title = jsonResponse.title;
                    const labels = jsonResponse.data.labels;
                    const datasets = jsonResponse.data.datasets;

                    // Reset the current chart
                    chart.data.datasets = [];
                    chart.data.labels = [];

                    // Load new data into the chart
                    chart.options.title.text = title;
                    chart.options.title.display = true;
                    chart.data.labels = labels;
                    datasets.forEach(dataset => {
                        chart.data.datasets.push(dataset);
                    });
                    chart.update();
                },
                error: () => console.log("Failed to fetch chart data from " + endpoint + "!")
            });
        }

        function loadAllCharts(year) {
            loadChart(InformeChart, `/panel/chart/informes/${year}/`);
            loadChart(TipoInformeChart, `/panel/chart/informes/tipo/${year}/`);
        }
    </script>
{% endblock custom-js %}


</body>

</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %} Ecogestion Ambiental Ltda {% endblock title %} </title>
    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'assets/images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'assets/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'assets/images/apple-touch-icon-114x114.png' %}">
    <!-- Web Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Hind:400,700%7cLora:400i%7cPoppins:500,600,700" rel="stylesheet">
    <!-- Bootstrap core CSS-->
    <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Plugins and Icon Fonts-->
    <link href="{% static 'assets/css/plugins.min.css' %}" rel="stylesheet">
    <!-- Template core CSS-->
    <link href="{% static 'assets/css/template.css' %}" rel="stylesheet">
</head>
<body>

<!-- Layout-->
<div class="layout">

    <!-- Header-->
    {% block header %}
    {% endblock header %}
    <!-- Header end-->

    <!-- Wrapper-->
    <div class="wrapper">

        <!-- Page Header-->
        {% block page-header %}
        {% endblock page-header %}
        <!-- Page Header end-->

        <!-- Nosotros-->
        {% block nosotros %}
        {% endblock nosotros %}
        <!-- Services end-->

        {% block servicios %}
        {% endblock servicios %}

        <!-- Team-->
        {% block equipo %}
        {% endblock equipo %}
        <!-- Team end-->

        <!-- certificaciones-->
        {% block certificaciones %}
        {% endblock certificaciones %}
        <!-- certificaciones-->

        {% block contacto %}
        {% endblock contacto %}

        <!-- Footer-->
        {% block footer %}
        {% endblock footer %}
        <!-- Footer end-->

        <a class="scroll-top" href="#top"><i class="fa fa-angle-up"></i></a>
    </div>
    <!-- Wrapper end-->
</div>
<!-- Layout end-->



<!-- Scripts-->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA0rANX07hh6ASNKdBr4mZH0KZSqbHYc3Q"></script>
<script src="{% static 'assets/js/plugins.min.js' %}"></script>
<script src="{% static 'assets/js/charts.js' %}"></script>
<script src="{% static 'assets/js/custom.min.js' %}"></script>

{% block custom-js %}
{% endblock custom-js %}

</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login Clientes | Ecogestion Ambiental Ltda</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/assets/css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">



            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <img src="{% static 'assets/images/logo-login.png' %}" style="width: 350px" alt="">
                                {% block content %}
                                {% endblock content %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>

    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'dashboard/assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'dashboard/assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'dashboard/assets/js/sb-admin-2.min.js' %}"></script>

{% block custom-js %}
{% endblock custom-js %}

</body>

</html>