apps/panel/urls.py
from django.conf.urls import url
from django.urls import path

from .views import PanelView, LogoutView, DetalleReclamoView, EnviarReclamoView, \
    form_enviar_reclamo_ajax, update_reclamo_ajax, respuesta_reclamo_ajax, ListarClientesView, \
    DetalleClienteView, crear_cliente_ajax, update_cliente_ajax, ContactoPanelView, \
    ServiciosPanelView, ServiciosEditarView, ServicioCrearView, EquipoListView, EquipoCreateView, \
    EquipoEditView, CertificacionListView, CertificacionCreateView, CertificacionEditView, ServiciosDeleteView, \
    EquipoDeleteView, CertificacionDeleteView, ContactonDeleteView, ListarUsuarios, crear_usuario_ajax, \
    update_usuario_ajax, DetalleUsuarioView, ClientesDeleteView, ListarInformesView, InformeEditView, \
    InformeCreateView, ListarInformesClienteView, login_success, get_filter_options, get_informe_chart, informe_per_category_chart

app_name = 'panel'

urlpatterns = [

    path('login_success/', login_success, name='login_success'),

    path('solicitudes/', PanelView, name="listar-solicitudes"),
    path('solicitud/<int:id>', DetalleReclamoView, name="detalle-reclamo"),
    path('solicitud/nuevo/', EnviarReclamoView, name="crear-reclamo"),
    path('form/form_ajax', form_enviar_reclamo_ajax, name='form-reclamo--ajax'),
    path('form/reclamo/form_ajax/<int:id>/', update_reclamo_ajax, name='form-update-reclamo-ajax'),
    path('form/respuesta/form_ajax/', respuesta_reclamo_ajax, name='form-respuesta-reclamo-ajax'),

    path('', ListarInformesView, name='panel'),
    path('my/informes/', ListarInformesClienteView, name="listar-informes-clientes"),
    path('informe/<int:id>', InformeEditView, name="editar-informe"),
    path('informe/nuevo/', InformeCreateView, name="crear-informe"),

    path('usuarios/', ListarUsuarios, name="listar-usuarios"),
    path('usuarios/nuevo/form_ajax/', crear_usuario_ajax, name="form-crear-usuario-por-ajax"),
    path('usuario/<int:id>', DetalleUsuarioView, name="detalle-usuario"),
    path('usuarios/editar/form_ajax/<int:id>/', update_usuario_ajax, name='form-update-usuario-ajax'),
    # path('usuarios/eliminar/<int:id>', UsuariosDeleteView, name="eliminar-usuario"),

    path('clientes/', ListarClientesView, name="listar-cliente"),
    path('cliente/<int:id>', DetalleClienteView, name="detalle-cliente"),
    path('cliente/nuevo/form_ajax/', crear_cliente_ajax, name='form-nuevo-cliente'),
    path('cliente/editar/form_ajax/<int:id>/', update_cliente_ajax, name='form-update-cliente-ajax'),
    path('cliente/eliminar/<int:id>/', ClientesDeleteView, name='eliminar-cliente'),

    path('modulo/contactos/', ContactoPanelView, name="listar-contactos"),
    path('modulo/contactos/eliminar/<int:id>', ContactonDeleteView, name="eliminar-contacto"),

    path('modulo/servcios/', ServiciosPanelView, name="listar-servicios"),
    path('modulo/servicio/<int:id>', ServiciosEditarView, name="detalle-servicio"),
    path('modulo/servicio/eliminar/<int:id>', ServiciosDeleteView, name="eliminar-servicio"),
    path('modulo/servicio/nuevo/', ServicioCrearView, name="crear-servicio"),

    path('modulo/equipo/', EquipoListView, name="listar-equipo"),
    path('modulo/equipo/nuevo/', EquipoCreateView, name="crear-equipo"),
    path('modulo/equipo/<int:id>', EquipoEditView, name="editar-equipo"),
    path('modulo/equipo/eliminar/<int:id>', EquipoDeleteView, name="eliminar-equipo"),

    path('modulo/certificaciones/', CertificacionListView, name="listar-certificacion"),
    path('modulo/certificaciones/nuevo/', CertificacionCreateView, name="crear-certificacion"),
    path('modulo/certificacion/<int:id>', CertificacionEditView, name="editar-certificacion"),
    path('modulo/certificacion/eliminar/<int:id>', CertificacionDeleteView, name="eliminar-certificado"),

    path('salir/', LogoutView, name="salir"),

    #url chart
    path('chart/filter-options/', get_filter_options, name='chart-filter-options'),
    path('chart/informes/<int:year>/', get_informe_chart, name='chart-informes'),
    path('chart/informes/tipo/<int:year>/', informe_per_category_chart, name='chart-informe-tipo'),
]

webecogestion/urls.py
import allauth
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', admin.site.urls),
    path('panel/',  include('apps.panel.urls', namespace='panel')),
    path('', include('apps.home.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth.account.views.LoginView, name='account_login'),
    path('tinymce/', include('tinymce.urls')),

    # url(r'^', include('apps.home.urls', namespace='home')),
    # url(r'^panel/', include('apps.panel.urls', namespace='panel')),
    # url(r'^accounts/', include('allauth.urls')),
    #
    # url(r'^accounts/login/', allauth.account.views.LoginView, name='account_login'),
    #
    # url(r'^tinymce/', include('tinymce.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

admin.site.site_header = 'Ecogestion Ambiental Ltda'

apps/informe/models.py
from django.db import models
from apps.cliente.models import Cliente

def upload_location_informe_pdf(instance, filename):
    filebase, extension = filename.split(".")
    return "informes/%s/%s.%s" % (instance.id, instance.id, extension)
    # return "%s/%s" % (instance.id, filename)

# Create your models here.
class Informe(models.Model):
    TIPO_INFORME = (
        ('1', 'Laboratorio de Ensayos'),
        ('2', 'Asesorías'),
        ('3', 'PVA'),
        ('4', 'Aguas Residuales'),
        ('5', 'Muestreo y/o Medición'),
        ('6', 'Aguas Subterráneas'),
        ('7', 'Agua Potable'),
    )
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre_informe = models.CharField(max_length=250, verbose_name="Nombre del Informe")
    tipo_informe = models.CharField(max_length=250, choices=TIPO_INFORME, verbose_name="Tipo de Informe")
    fecha_muestreo = models.DateField()
    fecha_recepcion = models.DateField()
    pdf_file = models.FileField(upload_to=upload_location_informe_pdf,
                                null=True,
                                blank=True,
                                editable=True)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    publicado = models.BooleanField(default=True)


    def __str__(self):
        return self.nombre_informe

    class Meta:
        verbose_name = 'Informe'
        verbose_name_plural = 'Informes'

apps/panel/models.py
from django.db import models

# Create your models here.

apps/cliente/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Cliente

class CrearClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['rut', 'razon_social', 'direccion', 'fono', 'contacto_comercial', 'usuario']


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'groups', 'is_active')

apps/informe/forms.py
from django import forms
from .models import Informe

class InformeForm(forms.ModelForm):
    class Meta:
        model = Informe
        exclude = ['fecha_publicacion']
        fields = ['cliente', 'nombre_informe', 'tipo_informe', 'fecha_muestreo', 'fecha_recepcion', 'pdf_file', 'publicado']

apps/informe/views.py
from django.shortcuts import render

# Create your views here.

apps/panel/views.py
import xlwt
import pytz
from django.contrib.auth import logout
from django.contrib.auth.models import User, Group
from django.core.mail import EmailMultiAlternatives
from django.db.models import Count
from django.db.models.functions import ExtractYear, ExtractMonth
from django.http import Http404, JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from allauth.account.decorators import verified_email_required
from django.template.loader import get_template

from apps.informe.models import Informe
from apps.informe.forms import InformeForm
from apps.informe.filter import InformeFilter
from apps.panel.utils import get_year_dict, months, colorPrimary, generate_color_palette
from apps.reclamo.models import Reclamo, Respuesta
from apps.reclamo.forms import ReclamoPanelForm, RespuestaPanelForm, EditarReclamoPanelForm
from apps.cliente.models import Cliente
from apps.cliente.forms import CrearClienteForm, UsuarioForm
from apps.reclamo.filters import ReclamoFilter
from apps.home.models import Contacto, Servcio, Equipo, Certificacion
from apps.home.forms import ServicioForm, EquipoForm, CertificadoForm

def LogoutView(request):
    logout(request)
    return redirect('/')

def login_success(request):
    """
    Redirects users based on whether they are in the admins group
    """
    if request.user.is_staff:
        # user is an admin
        return redirect("panel:panel")
    else:
        return redirect("panel:listar-informes-clientes")

@verified_email_required
def PanelView(request):
    data = dict()

    data['mi_reclamo'] = Reclamo.objects.filter(cliente__usuario=request.user).order_by('-id')

    reclamos_staff = Reclamo.objects.all().order_by('-id')

    data['reclamos_staff'] = reclamos_staff

    reclamos_filter = ReclamoFilter(request.GET, queryset=reclamos_staff)

    data['filter'] = reclamos_filter

    if request.method == 'GET' and 'accion_requerida' in request.GET:

        if request.GET['accion_requerida'] == 'exportar_datos':

            response = HttpResponse(content_type='application/ms-excel')
            response['Content-Disposition'] = 'attachment; filename="reclamos.xls"'
            wb = xlwt.Workbook(encoding='utf-8')
            ws = wb.add_sheet('Registros')

            # Sheet header, first row
            row_num = 0

            font_style = xlwt.XFStyle()
            font_style.font.bold = True

            columns = ['Fecha', 'Tipo de Solicitud', 'Categoría', 'Cliente', 'Estado']

            for col_num in range(len(columns)):
                ws.write(row_num, col_num, columns[col_num], font_style)

            # Sheet body, remaining rows
            font_style = xlwt.XFStyle()

            for registro in reclamos_filter.qs:
                row_num += 1
                ws.write(row_num, 0, '{}/{}/{}'.format(registro.fecha_ingreso.day, registro.fecha_ingreso.month,
                                                       registro.fecha_ingreso.year), font_style)
                ws.write(row_num, 1, registro.get_tipo_solicitud_display(), font_style)
                ws.write(row_num, 2, registro.get_categoria_display(), font_style)
                ws.write(row_num, 3, registro.cliente.razon_social, font_style)
                ws.write(row_num, 4, registro.get_estado_display(), font_style)

            wb.save(response)
            return response

    return render(request, 'panel.html', data)

@verified_email_required
def DetalleReclamoView(request, id):
    data = dict()

    detalle_reclamo = Reclamo.objects.get(pk=id)

    if request.user.id == detalle_reclamo.cliente.usuario.id or request.user.is_staff:

        data['form_reclamo'] = EditarReclamoPanelForm(instance=detalle_reclamo)

        data['pk_reclamo'] = id

        data['detalle_reclamo'] = detalle_reclamo

        data['mi_respuesta'] = Respuesta.objects.filter(reclamo_id=id)

        form_respuesta = RespuestaPanelForm()
        form_respuesta.fields['reclamo'].initial = id
        form_respuesta.fields['usuario_interno'].initial = request.user

        data['form_respuesta'] = form_respuesta

        return render(request, 'panel-detalle-reclamo.html', data)
    else:
        raise Http404

@verified_email_required
def EnviarReclamoView(request):

    data = dict()

    mi_cliente = Cliente.objects.get(usuario=request.user)

    form = ReclamoPanelForm()
    form.fields['estado'].initial = 1
    form.fields['cliente'].initial = mi_cliente.id

    data['form'] = form
    data['mi_cliente'] = mi_cliente

    return render(request, 'crear-reclamo.html', data)

@verified_email_required
def form_enviar_reclamo_ajax(request):
    """
    Funcion que valida un formulario mediante ajax
    :param request: request.POST
    :return : Json
    """
    data = dict()

    correo_segun_solicitud = {'1': 'aaguilera@ecogestionambiental.cl',
                              '2': 'aaguilera@ecogestionambiental.cl',
                              '3': 'laboratorio@ecogestionambiental.cl'}

    mi_cliente = Cliente.objects.get(usuario=request.user)

    if request.method == 'POST':
        form = ReclamoPanelForm(request.POST)
        if form.is_valid():
            # respuesta para el js
            data['respuesta'] = 'ok'

            # guardo la informacion de la solicitud
            form.save()

            # obtengo la informacion
            tipo_solicitud = request.POST['tipo_solicitud']
            estado = request.POST['estado']
            categoria = request.POST['categoria']
            texto = request.POST['texto']

            template1 = get_template('email/detalle-email-reclamo.html')
            template2 = get_template('email/notificacion-reclamo-cliente.html')


            # buscar el label de la sede
            label_tipo_solicitud = ''
            for x in Reclamo.TIPO_SOLICITUD:
                if x[0] == tipo_solicitud:
                    label_tipo_solicitud = x[1]

            # buscar el label de la tipo_discapacidad
            label_estado = ''
            for x in Reclamo.ESTADO:
                if x[0] == estado:
                    label_estado = x[1]

            label_categoria = ''
            for x in Reclamo.CAT:
                if x[0] == categoria:
                    label_categoria = x[1]

            ctx = {
                'cliente': mi_cliente.razon_social,
                'tipo_solicitud': label_tipo_solicitud,
                'estado': label_estado,
                'categoria': label_categoria,
                'texto': texto,
                'email': mi_cliente.usuario.email,

            }

            contenido1 = template1.render(ctx)
            contenido2 = template2.render(ctx)

            msg1 = EmailMultiAlternatives(
                'Nuevo ingreso de solicitud',
                contenido1,
                'noresponder@ecogestionambiental.cl',
                [correo_segun_solicitud[str(tipo_solicitud)],'admin@ecogestionambiental.cl', 'jmoscoso@ecogestionambiental.cl'],
            )
            msg1.attach_alternative(contenido1, "text/html")

            msg1.send()

            msg2 = EmailMultiAlternatives(
                'Nuevo ingreso de solicitud',
                contenido2,
                'noresponder@ecogestionambiental.cl',
                [mi_cliente.usuario.email],
            )
            msg2.attach_alternative(contenido2, "text/html")

            msg2.send()

        else:
            data['respuesta'] = 'error'
            mensaje_error = '<strong>Campos requeridos:</strong> <br>'
            for e in form.errors:
                mensaje_error = mensaje_error + ' [{}] '.format(e)
            data['mensaje'] = mensaje_error
    else:
        data['respuesta'] = 'error'

    return JsonResponse(data)

@verified_email_required
def update_reclamo_ajax(request, id):
    data = dict()

    detalle_reclamo = Reclamo.objects.get(pk=id)

    if request.method == 'POST':
        form_reclamo = EditarReclamoPanelForm(request.POST, instance=detalle_reclamo)
        if form_reclamo.is_valid():
            data['respuesta'] = 'ok'
            form_reclamo.save()
        else:
            data['respuesta'] = 'error'
            mensaje_error = '<strong>Campos requeridos:</strong> <br>'
            for e in form_reclamo.errors:
                mensaje_error = mensaje_error + ' [{}] '.format(e)
            data['mensaje'] = mensaje_error
    else:
        data['respuesta'] = 'error'
        data['form_reclamo'] = EditarReclamoPanelForm(request.POST, instance=detalle_reclamo)

    return JsonResponse(data)

@verified_email_required
def respuesta_reclamo_ajax(request):
    data = dict()

    # respuesta = Respuesta.objects.get(reclamo_id=id)

    if request.method == 'POST':
        form_respuesta = RespuestaPanelForm(request.POST)
        if form_respuesta.is_valid():
            data['respuesta'] = 'ok'
            respuesta_new = form_respuesta.save()

            # obtengo la informacion
            template1 = get_template('email/respuesta-reclamo.html')

            # buscar el label de la tipo_discapacidad

            label_estado = ''
            for x in Reclamo.ESTADO:
                if x[0] == respuesta_new.reclamo.estado:
                    label_estado = x[1]

            ctx = {
                'detalle_respuesta': respuesta_new.detalle_respuesta,
                'fecha_respuesta': respuesta_new.fecha_respuesta,
                'reclamo_id': respuesta_new.reclamo.pk,
                'reclamo_estado': label_estado,
                'cliente': respuesta_new.reclamo.cliente.razon_social
            }

            contenido1 = template1.render(ctx)

            msg1 = EmailMultiAlternatives(
                'Respuesta a requerimento',
                contenido1,
                'noresponder@ecogestionambiental.cl',
                [respuesta_new.reclamo.cliente.usuario.email],
            )
            msg1.attach_alternative(contenido1, "text/html")

            msg1.send()


        else:

apps/panel/templates/clientes.html
{% extends 'base-dashboard.html' %}
{% load staticfiles %}

{% block sidebar %}
    {% include 'include/sidebar.html' %}
{% endblock sidebar %}

{% block panel-title %}
    {% include 'include/panel-title.html' %}
{% endblock panel-title %}

{% block nav %}
    {% include 'include/nav.html' %}
{% endblock nav %}

{% block content %}
   {% include 'include/tabla-clientes.html' %}
{% endblock content %}

{% block footer %}
    {% include 'include/footer-panel.html' %}
{% endblock footer %}
x
{% block custom-js %}
     <script src="{% static 'cliente/js/cliente.js' %}"></script>
{% endblock custom-js %}

apps/panel/templates/crear-reclamo.html
{% extends 'base-dashboard.html' %}

{% block sidebar %}
    {% include 'include/sidebar.html' %}
{% endblock sidebar %}

{% block panel-title %}
    {% include 'include/panel-title.html' %}
{% endblock panel-title %}

{% block nav %}
    {% include 'include/nav.html' %}
{% endblock nav %}

{% block content %}
   {% include 'include/form-crear-reclamo.html' %}
{% endblock content %}

{% block footer %}
    {% include 'include/footer-panel.html' %}
{% endblock footer %}

{% block custom-js %}
    <script>

        $(document).ready(function(){

            //form-contacto
            $('#div-errores').hide();

            $("#form-reclamo").on("submit", function(){
                let csrftoken = $("[name=csrfmiddlewaretoken]").val();
                $('#btn-form-reclamo').html('Enviando...');
                $.ajax({
                    url: "{% url 'panel:form-reclamo--ajax' %}",
                    type: 'POST',
                    data: $("#form-reclamo").serialize(),
                    headers:{
                        "X-CSRFToken": csrftoken
                    },
                    success:function(data){
                        if(data.respuesta=='ok'){
                            let emisor = $('#cliente').val();
                            $('#emisor').html(emisor);
                            $('#btn-form-reclamo').html('Enviar');
                            $('#ContactonModal').modal('show');
                            $('#form-reclamo')[0].reset();
                            $('#div-errores').hide();
                        }
                        else{//data.respuesta=='error'
                            $('#id_error').html('');
                            $('#id_error').html(data.mensaje);
                            $('#btn-form-reclamo').html('Enviar');
                            $('#div-errores').show();
                        }
                    }
                });
                return false;
            });

        });
    </script>
{% endblock custom-js %}

apps/panel/templates/detalle-reclamo.html
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Detalles</h6>
                {% if request.user.is_staff %}
                    <div class="pull-right">
                        <a data-toggle="modal" data-target="#modal_reclamo">
                            <i class="fa fa-2x fa-edit"></i>
                        </a>
                    </div>
                {% endif %}
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% include 'include/tabla-detalle-reclamo.html' %}
            </div>
        </div>
    </div>
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Respuestas</h6>
                {% if request.user.is_staff %}
                    <div class="pull-right">
                        <a data-toggle="modal" data-target="#modal_respuesta">
                            <i class="fa fa-2x fa-plus"></i>
                        </a>
                    </div>
                {% endif %}
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% include 'include/tabla-detalle-respuesta.html' %}
            </div>
        </div>
    </div>
</div>


<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal_reclamo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Editar información</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" method="POST" id="form-edit-reclamo" data-url="{% url 'panel:form-update-reclamo-ajax' pk_reclamo %}"> {% csrf_token %}
                <div class="modal-body">
                    {{ form_reclamo|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary" id="btn-form-edit-reclamo">Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modal_respuesta" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Crear respuesta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form role="form" method="POST" id="form-respuesta-reclamo" data-url="{% url 'panel:form-respuesta-reclamo-ajax' %}"> {% csrf_token %}
                <div class="modal-body">
                    {{ form_respuesta|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary" id="btn-form-respuesta-reclamo">Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>

apps/panel/templates/informes.html
{% extends 'base-dashboard.html' %}
{% load staticfiles %}

{% block sidebar %}
    {% include 'include/sidebar.html' %}
{% endblock sidebar %}

{% block panel-title %}
    {% include 'include/panel-title.html' %}
{% endblock panel-title %}

{% block nav %}
    {% include 'include/nav.html' %}
{% endblock nav %}

{% block content %}
   {% include 'include/tabla-informes.html' %}
{% endblock content %}

{% block footer %}
    {% include 'include/footer-panel.html' %}
{% endblock footer %}

apps/panel/templates/panel-contactos.html
{% extends 'base-dashboard.html' %}

{% block sidebar %}
    {% include 'include/sidebar.html' %}
{% endblock sidebar %}

{% block panel-title %}
    {% include 'include/panel-title.html' %}
{% endblock panel-title %}

{% block nav %}
    {% include 'include/nav.html' %}
{% endblock nav %}

{% block content %}
    {% include 'include/tabla-contactos.html' %}
{% endblock content %}

{% block footer %}
    {% include 'include/footer-panel.html' %}
{% endblock footer %}

apps/panel/templates/panel-crear-certificacion.html
{% extends 'base-dashboard.html' %}
{% load staticfiles %}

{% block sidebar %}
    {% include 'include/sidebar.html' %}
{% endblock sidebar %}

{% block panel-title %}
    {% include 'include/panel-title.html' %}
{% endblock panel-title %}

{% block nav %}
    {% include 'include/nav.html' %}
{% endblock nav %}

{% block content %}
    {% include 'include/form-crear-certificacion.html' %}
{% endblock content %}

{% block footer %}
    {% include 'include/footer-panel.html' %}
{% endblock footer %}

{% block custom-js %}
{% endblock custom-js %}

apps/panel/templates/table-reclamos.html
{% if request.user.is_staff %}
    <div class="row">

        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Filtros</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% include 'include/filter-staff.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Registro Solicitudes</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">

                    {% include 'include/tabla-reclamos-staff.html' %}

                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="row">

        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Registro de Solicitudes</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Acciones:</div>
                            <a class="dropdown-item" href="{% url 'panel:crear-reclamo' %}">Ingresar una solicitud</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">

                    {% include 'include/tabla-reclamos.html' %}

                </div>
            </div>
        </div>
    </div>
{% endif %}